# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'PzDuoyCJDylaXqf13-7ql5Fd3MBOgRAJ'
  redis: 'WeEea9xRwtAYHHe8UH9_-iqEJoL1fkIT'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: '_8c8wAbuU5VnypZRn0eN8ucEmA09kpFw'

test:
  database: 'fhlcPOZwhUPZBJq2ugu28ivDU1zju8eo'
  redis: 'WXU0YjLQAqXicVskX6tnbB2txr892GZo'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: '6vnvJqbeGWEo-tg9AVY47IPq6tz680BW'
  serviceSecret: 'A-4jck2IOrSRwVCHPYIlR7a68FQv4BhE'

# Passwords used in production mode.
production:
  database: 'AVNS_bzpB2irtfc-oNxhMkZl'
  redis: ''
  serviceSecret: 'kD83jskd92Kskd82Jskd83JsKdlPq92'